config/routes.rb
Detour::Engine.routes.draw do
  get  "/flags/:flaggable_type" => "flags#index", as: "flags"
  post "/flags/:flaggable_type" => "flags#update"

  resources :features, only: [:create, :destroy]
  resources :groups, only: [:index, :show, :create, :update, :destroy]

  scope "/:flag_type/:feature_name" do
    get    ":flaggable_type"     => "flaggable_flags#index",   as: "flaggable_flags"
    put    ":flaggable_type"     => "flaggable_flags#update"
    delete ":flaggable_type/:id" => "flaggable_flags#destroy", as: "flaggable_flag"
  end

  root to: "application#index"
end

app/models/detour/concerns/countable_flag.rb
module Detour::Concerns
  module CountableFlag
    extend ActiveSupport::Concern

    included do
      after_save    :step_count
      after_destroy :step_count

      private

      def step_count
        count = feature.send("#{flag_type}_count_for", flaggable_type.tableize)
        count = destroyed? ? count - 1 : count + 1
        feature.send("#{flag_type}_counts")[flaggable_type.tableize] = count
        feature.save!
      end
    end
  end
end

app/models/detour/concerns/custom_human_attributes.rb
module Detour::Concerns
  module CustomHumanAttributes
    extend ActiveSupport::Concern

    included do
      @human_attribute_names = {}

      class << self
        alias :original_human_attribute_name :human_attribute_name
      end

      def self.human_attribute_name(*args)
        @human_attribute_names[args[0]] || original_human_attribute_name(*args)
      end

      def self.set_human_attribute_name(key, name)
        @human_attribute_names[key] = name
      end
    end
  end
end

app/models/detour/concerns/keepable.rb
module Detour::Concerns
  module Keepable
    extend ActiveSupport::Concern

    included do
      attr_writer :to_keep
    end

    def to_keep
      @to_keep || (!marked_for_destruction? && !new_record?)
    end

    def keep_or_destroy(params = {})
      if params["to_keep"] == "1"
        self.to_keep = true
      else
        mark_for_destruction
      end
    end
  end
end

app/models/detour/database_group_flag.rb
class Detour::DatabaseGroupFlag < Detour::Flag
  include Detour::Concerns::Keepable

  validates_presence_of   :group_id
  validates_presence_of   :flaggable_type
  validates_uniqueness_of :feature_id, scope: :group_id

  attr_accessible :group_id

  belongs_to :group
  has_many   :memberships, through: :group

  def members
    flaggable_class.joins(%Q{INNER JOIN "detour_memberships" ON "#{flaggable_class.table_name}"."id" = "detour_memberships"."member_id"}).where(detour_memberships: { group_id: group.id })
  end

  def group_name
    group.name
  end

  def group_type
    "database"
  end

  private

  def flaggable_class
    flaggable_type.constantize
  end
end

app/models/detour/defined_group.rb
class Detour::DefinedGroup
  attr_reader :name
  alias :id :name

  def initialize(name, test)
    @name = name.to_s
    @test = test
  end

  def to_s
    name
  end

  def test(arg)
    @test.call(arg)
  end

  def self.by_type(type)
    Detour.config.defined_groups.fetch(type.to_s, {}).with_indifferent_access
  end
end

app/models/detour/defined_group_flag.rb
# A group of flaggable records of a given class may be flagged into a feature
# with this class.
class Detour::DefinedGroupFlag < Detour::Flag
  include Detour::Concerns::Keepable

  validates_presence_of   :group_name
  validates_uniqueness_of :feature_id, scope: [:flaggable_type, :group_name]

  attr_accessible :group_name

  def group
    find_group || build_group
  end

  def group_type
    "defined"
  end

  private

  def find_group
    Detour::DefinedGroup.by_type(flaggable_type)[group_name]
  end

  def build_group
    Detour::DefinedGroup.new(group_name, ->{})
  end
end

app/models/detour/feature.rb
# Represents an individual feature that may be rolled out to a set of records
# via individual flags, percentages, or defined groups.
class Detour::Feature < ActiveRecord::Base
  include Detour::Concerns::CustomHumanAttributes

  self.table_name = :detour_features

  serialize :flag_in_counts, JSON
  serialize :opt_out_counts, JSON

  has_many :flag_in_flags,        dependent: :destroy
  has_many :defined_group_flags,  dependent: :destroy
  has_many :database_group_flags, dependent: :destroy
  has_many :percentage_flags,     dependent: :destroy
  has_many :opt_out_flags,        dependent: :destroy
  has_many :flags,                dependent: :destroy

  validates_presence_of   :name
  validates_uniqueness_of :name
  validates_format_of     :name, with: /\A[\w-]+\Z/

  attr_accessible :name

  # Returns an instance variable intended to hold an array of the lines of code
  # that this feature appears on.
  #
  # @return [Array<String>] The lines that this rollout appears on (if
  #   {Detour::Feature.with_lines} has already been called).
  def lines
    @lines ||= []
  end

  def to_s
    name
  end

  # Returns the number of flag-ins for a given type.
  #
  # @example
  #   feature.flag_in_count_for("users")
  #
  # @return [Fixnum] The number of flag-ins for the given type.
  def flag_in_count_for(type)
    flag_in_counts[type] || 0
  end

  # Returns the number of opt-outs for a given type.
  #
  # @example
  #   feature.opt_out_count_for("users")
  #
  # @return [Fixnum] The number of opt-outs for the given type.
  def opt_out_count_for(type)
    opt_out_counts[type] || 0
  end

  # Return an array of both every feature in the database as well as every
  # feature that is checked for in `@feature_search_dirs`. Features that are checked
  # for but not persisted will be returned as unpersisted instances of this
  # class. Each instance returned will have its `@lines` set to an array
  # containing every line in `@feature_search_dirs` where it is checked for.
  #
  # @return [Array<Detour::Feature>] Every persisted and
  #   checked-for feature.
  def self.with_lines
    hash = all.each_with_object({}) { |feature, hash| hash[feature.name] = feature }

    Dir[*Detour.config.feature_search_dirs].each do |path|
      next unless File.file? path

      File.open path do |file|
        file.each_line.with_index(1) do |line, i|
          line.scan(feature_search_regex).each do |match, _|
            (hash[match] ||= new(name: match)).lines << "#{path}#L#{i}"
          end
        end
      end
    end

    hash.values.sort_by(&:name)
  end

  def self.feature_search_regex
    Detour.config.feature_search_regex || /\.has_feature\?\s*\(?[:"]([\w-]+)/
  end
  private_class_method :feature_search_regex
end

app/models/detour/flag.rb
# Indicates that a specific feature has been rolled out to an individual
# Table for storing flaggable flag-ins, group flag-ins, or percentage-based
# flag-ins.
class Detour::Flag < ActiveRecord::Base
  self.table_name = :detour_flags

  belongs_to :feature

  validates_presence_of :feature
  validates_presence_of :flaggable_type

  attr_accessible :flaggable_type

  scope :without_opt_outs, ->(record) {
    where(flaggable_type: record.class.to_s).where <<-SQL
      feature_id NOT IN (
        SELECT feature_id FROM detour_flags
          WHERE detour_flags.type = 'Detour::OptOutFlag'
          AND   detour_flags.flaggable_type = '#{record.class.to_s}'
          AND   detour_flags.flaggable_id   = '#{record.id}'
      )
    SQL
  }

  private

  def flag_type
    self.class.to_s.underscore.gsub("detour/", "").split("_")[0..-2].join("_")
  end
end

app/models/detour/flag_in_flag.rb
# An individual record of a certain type may be flagged into a feature with
# this class.
class Detour::FlagInFlag < Detour::FlaggableFlag
  validates_uniqueness_of :feature_id, scope: [:flaggable_type, :flaggable_id]
end

app/models/detour/flaggable_flag.rb
class Detour::FlaggableFlag < Detour::Flag
  include Detour::Concerns::CountableFlag

  belongs_to :flaggable, polymorphic: true

  validates_presence_of :flaggable

  attr_accessor   :flaggable_key
  attr_accessible :flaggable
  attr_accessible :flaggable_key

  before_validation :set_flaggable

  private

  def set_flaggable
    unless flaggable || !flaggable_key
      self.flaggable_id = flaggable_type.constantize.flaggable_find!(flaggable_key).id
    end
  rescue ActiveRecord::RecordNotFound
    errors.add(flaggable_type, "\"#{flaggable_key}\" could not be found")
    false
  end
end

app/models/detour/group.rb
class Detour::Group < ActiveRecord::Base
  include Detour::Concerns::CustomHumanAttributes

  validates :name,           presence: true, uniqueness: { scope: :flaggable_type }
  validates :flaggable_type, presence: true, inclusion: { in: Detour.config.flaggable_types }
  has_many :memberships, dependent: :destroy
  has_many :database_group_flags, dependent: :destroy

  accepts_nested_attributes_for :memberships, allow_destroy: true

  attr_accessible :name, :flaggable_type, :memberships_attributes

  def to_s
    name
  end

  def flaggable_class
    flaggable_type.constantize
  end
end

app/models/detour/group_flag.rb
# A group of flaggable records of a given class may be flagged into a feature
# with this class.
class Detour::GroupFlag < Detour::Flag
  include Detour::Concerns::Keepable

  validates_presence_of   :group_name
  validates_uniqueness_of :feature_id, scope: [:flaggable_type, :group_name]

  attr_accessible :group_name
end

app/models/detour/membership.rb
class Detour::Membership < ActiveRecord::Base
  validates :group_id,    presence: true
  validates :member_id,   presence: true, uniqueness: { scope: :group_id }
  validates :member_key,  presence: true, unless: -> { member_id }
  validates :member_type, presence: true
  validate  :validate_member_type

  attr_accessor   :member_key
  attr_accessible :group_id
  attr_accessible :member_key
  attr_accessible :member_type

  default_scope { order("member_type ASC") }

  belongs_to :group
  belongs_to :member, polymorphic: true

  before_validation :set_member

  private

  def member_class
    group.flaggable_class
  end

  def set_member
    unless member || !member_key
      self.member_type = group.flaggable_type
      self.member_id   = member_class.flaggable_find!(member_key).id
    end
  rescue ActiveRecord::RecordNotFound
    errors.add(member_type, "\"#{member_key}\" could not be found")
    false
  end

  def validate_member_type
    unless group && member_type == group.flaggable_type
      errors.add :member_type, "must match the group's flaggable_type"
    end
  end
end

app/models/detour/opt_out_flag.rb
# Ensures that a feature will never be available to the associated record,
# even in the case of, for example, a 100% flag.
class Detour::OptOutFlag < Detour::FlaggableFlag
  validates_uniqueness_of :feature_id, scope: [:flaggable_type, :flaggable_id]
end

app/models/detour/percentage_flag.rb
# A percentage of flaggable records of a given class may be flagged into a feature
# with this class.
class Detour::PercentageFlag < Detour::Flag
  validates_presence_of     :percentage
  validates_numericality_of :percentage, greater_than: 0, less_than_or_equal_to: 100
  validates_uniqueness_of   :feature_id, scope: :flaggable_type

  attr_accessible :percentage
end

app/controllers/detour/application_controller.rb
class Detour::ApplicationController < ActionController::Base
  def index
  end

  private

  def ensure_flaggable_type_exists
    unless Detour.config.flaggable_types.map(&:tableize).include? params[:flaggable_type]
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/detour/features_controller.rb
class Detour::FeaturesController < Detour::ApplicationController
  def create
    @feature = Detour::Feature.new(params[:feature])

    if @feature.save
      flash[:notice] = "Your feature has been successfully created."
      render "detour/shared/success"
    else
      @model = @feature
      render "detour/shared/error"
    end
  end

  def destroy
    @feature = Detour::Feature.find(params[:id])
    @feature.destroy
    flash[:notice] = "Feature #{@feature.name} has been deleted."
    redirect_to flags_path(params[:flaggable_type])
  end
end

app/controllers/detour/flaggable_flags_controller.rb
require "indefinite_article"

class Detour::FlaggableFlagsController < Detour::ApplicationController
  include Detour::FlaggableFlagsHelper

  before_filter :ensure_flaggable_type_exists
  before_filter :ensure_flag_type_exists

  def index
    @feature = Detour::Feature.where(name: params[:feature_name]).first_or_create!
  end

  def update
    @feature = Detour::Feature.find_by_name!(params[:feature_name])

    if @feature.update_attributes(params[:feature])
      flash[:notice] = "Your #{flag_noun.pluralize} have been updated"
      redirect_to flaggable_flags_path flag_type: params[:flag_type], feature_name: params[:feature_name], flaggable_type: params[:flaggable_type]
    else
      render :index
    end
  end

  private

  def ensure_flag_type_exists
    unless %w[flag-ins opt-outs].include? params[:flag_type]
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/detour/flags_controller.rb
class Detour::FlagsController < Detour::ApplicationController
  before_filter :ensure_flaggable_type_exists

  def index
    @flag_form = Detour::FlagForm.new(params[:flaggable_type])
  end

  def update
    @flag_form = Detour::FlagForm.new(params[:flaggable_type])

    if @flag_form.update_attributes(params)
      flash[:notice] = "Your flags have been successfully updated."
      redirect_to flags_path
    else
      render :index
    end
  end
end

app/controllers/detour/groups_controller.rb
class Detour::GroupsController < Detour::ApplicationController
  def index
    @groups = Detour::Group.all
  end

  def show
    @group = Detour::Group.find(params[:id])
  end

  def create
    @group = Detour::Group.new(params[:group])

    if @group.save
      flash[:notice] = "Your group has been successfully created."
      render "detour/shared/success"
    else
      @model = @group
      render "detour/shared/error"
    end
  end

  def update
    @group = Detour::Group.find(params[:id])

    if @group.update_attributes(params[:group])
      flash[:notice] = "Your group has been successfully updated."
      redirect_to group_path @group
    else
      render :show
    end
  end

  def destroy
    @group = Detour::Group.find(params[:id])
    @group.destroy
    flash[:notice] = "Group \"#{@group.name}\" has been deleted."
    redirect_to groups_path
  end
end

app/views/detour/flags/_feature_form.html.erb
<%= content_tag_for :tr, feature do %>
  <%= fields_for "features[#{feature}]", feature do |feature_form| %>
    <td>
      <% unless feature.new_record? %>
        <button type="button" class="btn btn-danger btn-xs delete-feature" data-path="<%= feature_path(feature.id, params: { flaggable_type: params[:flaggable_type] }) %>">
          <span class="glyphicon glyphicon-remove"></span>
        </button>
      <% end %>
    </td>

    <td><%= feature %></td>

    <td>
      <% if feature.lines.any? %>
        <i class="feature-lines glyphicon glyphicon-ok" data-prefix="<%= github_prefix %>" data-lines="<%= feature.lines.join(",") %>"></i>
        (<%= pluralize(feature.lines.count, "use") %>)
      <% else %>
        <i class="glyphicon glyphicon-ban-circle"></i>
      <% end %>
    </td>

    <%= render partial: "detour/shared/spacer_cells", locals: { tag: "td" } %>

    <% @flag_form.group_flags_for(feature).each do |flag| %>
      <%= feature_form.fields_for "#{params[:flaggable_type]}_#{flag.group_type}_group_flags_attributes[#{flag.group_name}]", flag do |group_flag_form| %>
        <%= group_flag_form.hidden_field :id %>
        <td><%= group_flag_form.check_box :to_keep, data: { toggle: "tooltip", placement: "top", original_title: "#{flag.group_name}" } %></td>
      <% end %>
    <% end %>

    <%= feature_form.fields_for "#{params[:flaggable_type]}_percentage_flag_attributes", feature.send("#{params[:flaggable_type]}_percentage_flag") do |percentage_flag_form| %>
      <td><%= percentage_flag_form.text_field :percentage, class: "form-control input-sm" %></td>
    <% end %>

    <td class="flag-in-count">
      <%= link_to flaggable_flags_path(flag_type: "flag-ins", feature_name: feature.name, flaggable_type: params[:flaggable_type]) do %>
        <%= feature.flag_in_count_for(params[:flaggable_type]) %>
      <% end %>
    </td>

    <td class="opt-out-count">
      <%= link_to flaggable_flags_path(flag_type: "opt-outs", feature_name: feature.name, flaggable_type: params[:flaggable_type]) do %>
        <%= feature.opt_out_count_for(params[:flaggable_type]) %>
      <% end %>
    </td>
  <% end %>
<% end %>

app/views/detour/flags/index.html.erb
<h1><%= params[:flaggable_type].classify %> Flags</h1>

<% if @flag_form.errors? %>
  <div class="panel panel-danger">
    <div class="panel-heading">Whoops! There were some errors saving your flags:</div>

    <div class="panel-body">
      <ul>
        <% @flag_form.features.each do |feature| %>
          <% feature.errors.full_messages.each do |msg| %>
              <li><strong><%= feature.name %>:</strong> <%= msg %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_tag do %>
  <%= table do %>
    <thead>
      <tr>
        <th></th>
        <th>Feature</th>
        <th>In Code?</th>

        <%= render partial: "detour/shared/spacer_cells", locals: { tag: "th" } %>

        <% @flag_form.groups.each do |group| %>
          <th>
            <span class="group-header">
              <% if group.is_a? Detour::Group %>
                <%= link_to group, group %>
              <% else %>
                <%= group %>
              <% end %>
            </span>
          </th>
        <% end %>

        <th class="percentage-header">Percentage</th>
        <th class="counter-header">Flag-ins</th>
        <th class="counter-header">Opt-outs</th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: "feature_form", collection: @flag_form.features, as: :feature %>
    </tbody>
  <% end %>

  <%= content_tag :span, "Create a Feature", class: "btn btn-default pull-left", data: { toggle: "modal", target: "#create-feature" } %>

  <div class="btn-group pull-right">
    <% if @flag_form.errors? %>
      <%= link_to "Cancel", request.path, class: "btn btn-default" %>
    <% end %>

    <%= submit_tag "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

<%= modal title: "Delete Feature", id: "delete-feature" do %>
  <p>Are you sure you want to delete <span class="feature-name"></span>?</p>

  <%= modal_footer do %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= link_to "Delete Feature", "javascript:void(0)", method: :delete, class: "btn btn-danger" %>
  <% end %>
<% end %>

<%= modal title: "Create a Feature", id: "create-feature", fade: true do %>
  <%= form_for Detour::Feature.new, remote: true do |form| %>
    <%= form.text_field :name, class: "form-control", placeholder: "feature_name" %>

    <%= modal_footer do %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= form.submit "Create Feature", class: "btn btn-primary" %>
    <% end %>
  <% end %>
<% end %>